### PR TITLE
Issue 16 enumerations

### LINKED ISSUE #16: Create Status Enumerations
Create Enumerations of the status members

File: file_status  --- new, parsed, processing, complete 
merchant: merchant_status -- new, validated, rejected, lexing,  processing, complete
url: url_status  -- new, processing, scoring, matched, match failed, error 

- [x] enumerations have been built for each member value
- [x] unit tests have been written to validate enumerations

### PR DESCRIPTION
**Pull request by andrewnisbet74**
Replaced the string status values with Enumerations backed by status integer values. 

-- Migrations to convert the fields from stings to integers
-- Updates to the models defining the Enumerations
-- Updates to the specs and factories to provide test coverage and make sure the existing tests still pass 

Closes #16 

@DeathMetalCoder

### CODE REVIEW

File: app/models/merchant.rb [hunk 1]
```diff
@@ -6,19 +6,26 @@ class Merchant < ApplicationRecord
   
   #Assocations
   has_many :urls
+
+  #Enumerations 
+  enum merchant_status: [:new_merchant, :validated, :rejected, :lexing, :lexing_complete, :processing, :complete]
```
Comment (DeathMetalCoder) [inline app/models/merchant.rb]: This is much cleaner than what I had. Nice! : )

**Comment by DeathMetalCoder** [comment]
👍

File: app/models/merchant_file.rb [hunk 2]
```diff
@@ -1,14 +1,17 @@
...
 class MerchantFile < ApplicationRecord
-  validates :file_status,
-  :inclusion  => { :in => [ 'PROCESSING', 'SUCCESSFUL', 'FAILED' ],
-    :message    => "%{value} is not a valid 'file_status' status" }
-    
+  #Validations
+  validates :file_status,  presence: true
+  
+  #Enumerations 
+  enum file_status: [:new_file, :parsed, :processing, :complete]
```
Comment (andrewnisbet74) [inline app/models/merchant_file.rb]: That is a good idea, I will add that.
